variable "vpc_id" {}
variable "image_name" {}
variable "image_owner" {}
variable "public_key_location" {}
variable "private_key_location" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "avail_zone" {}
variable "env_prefix" {}
variable "my_ip" {}